### ISSUE TITLE
Doesn't run on Ubuntu 19.10

### ISSUE THREAD

**Issue by alexkreidler** [jeansaad/chalet#11]
```
alex@alex-brain ~/c/r/a/t/debug (content-negotiation ⚡↩=)> chalet add "./actix-example-server" --name schemas
Create ~/.chalet/servers/schemas.json
Output No log file specified (use '-o app.log')
Port Random port (use '-p 1337' to set a fixed port)
alex@alex-brain ~/c/r/a/t/debug (content-negotiation ⚡↩=)> ls
actix-example-server*  actix-example-server.d  actix-server*  actix-server.d  build/  deps/  examples/  incremental/  libactix_files.d  libactix_files.rlib  libactix_web.d  libactix_web.rlib
alex@alex-brain ~/c/r/a/t/debug (content-negotiation ⚡↩=)> chalet ls
schemas
~/c2/rust/actix-web/target/debug
./actix-example-server
alex@alex-brain ~/c/r/a/t/debug (content-negotiation ⚡↩=)> chalet run schemas
Create ~/.chalet/servers/debug.json
sh: 1: schemas: not found
(node:8995) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at startServer (/home/alex/.config/yarn/global/node_modules/chalet/lib/cli/run.js:60:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8995) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8995) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Thought I'd report this here because Hotel [isn't really maintained anymore](https://github.com/typicode/hotel/issues/363). I'd appreciate any of your thoughts or if you could take a stab at fixing this.

Let me know if you need any more details. Thanks!

<details>
<summary>Environment</summary>

Kernel (`uname -a`): `Linux alex-brain 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
OS Version (`cat /etc/os-release`): 
```
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
```
Node environment:
```
$ node --version
v12.18.2
$ npm --version
6.14.5
$ yarn --version
1.22.0
```
</details>

**Comment by jeansaad** [comment]
Thanks for the bug report! Will have a look and try to reproduce. Any reason why you think it's just an Ubuntu 19.10 issue only? Have you tried it on any other distros? I have ArchLinux so I'll try to reproduce with that!

**Comment by jeansaad** [comment]
@alexkreidler, I've had a deeper look at your command and the issue seems to be incorrect usage.

The `run` command is a dynamic command that will instantly run whichever command you have and add an entry to the chalet servers file. By invoking `chalet run schemas`, you are telling chalet that you want to run a command named `schemas`, hence the error:
```
sh: 1: schemas: not found
```
If you want to run a command dynamically, use:
```
chalet run "./actix-example-server" --name schemas
```
But, be warned that once this stops, the configuration will be removed from Chalet. I would advise using the original add command to make this permanent in your settings and the service will start once you hit https://schemas.localhost

Let me know if you have any more questions and if this has solved your issue, feel free to close this.

**Comment by alexkreidler** [comment]
Ah, I overlooked that! Thanks for pointing it out and sorry to take up your time.

**Comment by jeansaad** [comment]
Not a problem! Glad you're able to use it now.
