### ISSUE TITLE
.localhost domains do not work on Windows

### ISSUE THREAD

**Issue by Spedwards** [jeansaad/chalet#16]
The TLDs do not work on Windows. `localhost:2000/app` works but `app.localhost` does not. I have setup the proxy according to the instructions.
![image](https://user-images.githubusercontent.com/3257096/109411459-62b6e080-79f6-11eb-9549-a4370aec9333.png)

I have restarted my browser and tried different browsers.

**Comment by ProjectInfinity** [comment]
Same issue on Linux.

**Comment by philipbjorge** [comment]
@Spedwards @ProjectInfinity --
This issue resolved for me after switching to the `.test` TLD -- https://github.com/jeansaad/chalet/issues/13
