### ISSUE TITLE
What would cause chalet to show a server as off?

### ISSUE THREAD

**Issue by Madd0g** [jeansaad/chalet#43]
I tried adding [colima](https://github.com/abiosoft/colima) to chalet (added the command `colima start`.

When I turn it on, it starts the process and looks normal, but the switch shows it as "off".

Is it because something is getting forked or switching pids or something? or could it be a simpler explanation?

Thanks

**Comment by jeansaad** [comment]
Hello, I don’t have much to go on in terms of how Colima works but it looks like that command doesn’t run indefinitely so that could be the reason why it doesn’t stay on.
